### ISSUE TITLE
third-party

### ISSUE THREAD

**Issue by jbensabat** [coin-or/minotaur#38]
Hello 
I have built Minotaur and it appears that I need the third-party 
I tried to get it from
wget http://www.ieor.iitb.ac.in/files/faculty/amahajan/minotaur/third-party/minotaur-0.3.0-third-party-win.tar.gz

it seems to be broken
any help would be appreciated
best
jac

**Comment by ashutoshmahajan** [comment]
The third-party script has now been updated to download the source-code of third-party software and compile them. Updated guidelines available here: https://minotaur-solver.github.io/#compile-win
